### ISSUE TITLE
org.h2.jdbc.JdbcSQLException: Das Objekt wurde bereits geschlossen

### ISSUE THREAD

**Issue by GiantTreeLP** [GiantTreeLP/GroundMCPlugin#16]
```
[22:47:38 WARN]: [GroundMC_Lobby_Plugin] Task #7 for GroundMC_Lobby_Plugin v1.4 generated an exception
org.h2.jdbc.JdbcSQLException: Das Objekt wurde bereits geschlossen
The object is already closed [90007-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:179) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:155) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:144) ~[?:?]
	at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3200) ~[?:?]
	at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:127) ~[?:?]
	at org.jetbrains.exposed.sql.Query$ResultIterator.hasNext(Query.kt:217) ~[?:?]
	at gtlp.groundmc.lobby.task.HidePlayersTask$run$1.invoke(HidePlayersTask.kt:60) ~[?:?]
	at gtlp.groundmc.lobby.task.HidePlayersTask$run$1.invoke(HidePlayersTask.kt:11) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:70) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:49) ~[?:?]
	at gtlp.groundmc.lobby.task.HidePlayersTask.run(HidePlayersTask.kt:16) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-625bc00-7dd77d7]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-625bc00-7dd77d7]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-625bc00-7dd77d7]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-625bc00-7dd77d7]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-625bc00-7dd77d7]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-625bc00-7dd77d7]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

**Comment by GiantTreeLP** [comment]
Error found and fixed.
