### ISSUE TITLE
Make Relationship Serializable

### ISSUE THREAD

**Issue by GiantTreeLP** [GiantTreeLP/GroundMCPlugin#8]
```
[21:13:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'friend' in plugin GroundMC_Lobby_Plugin v1.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1353) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.io.NotSerializableException: gtlp.groundmc.lobby.Relationship
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[?:1.8.0_121]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_121]
	at gtlp.groundmc.lobby.database.table.Relationships$addRelationship$1$1.invoke(Relationships.kt:57) ~[?:?]
	at gtlp.groundmc.lobby.database.table.Relationships$addRelationship$1$1.invoke(Relationships.kt:21) ~[?:?]
	at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:26) ~[?:?]
	at gtlp.groundmc.lobby.database.table.Relationships$addRelationship$1.invoke(Relationships.kt:50) ~[?:?]
	at gtlp.groundmc.lobby.database.table.Relationships$addRelationship$1.invoke(Relationships.kt:21) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:70) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:49) ~[?:?]
	at gtlp.groundmc.lobby.database.table.Relationships.addRelationship(Relationships.kt:48) ~[?:?]
	at gtlp.groundmc.lobby.database.table.Relationships.addRelationship(Relationships.kt:36) ~[?:?]
	at gtlp.groundmc.lobby.commands.CommandFriend.addFriend(CommandFriend.kt:217) ~[?:?]
	at gtlp.groundmc.lobby.commands.CommandFriend.execute(CommandFriend.kt:65) ~[?:?]
	at gtlp.groundmc.lobby.LobbyMain.onCommand(LobbyMain.kt:146) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-625bc00-186c351]
	... 15 more
```

This can be fixed by making `Relationship` `Serializable`

**Comment by GiantTreeLP** [comment]
Not needed as I have removed the offending code (it's not needed)

**Comment by GiantTreeLP** [comment]
Requires additional table upgrades.
